name: Frutz

on: workflow_dispatch

jobs:
  fruitz:
    name: Fruit, Néo
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        fruits: [Banane, Moule, Pêche]
        personnes: [Remi, Kevin, Sasuke, Dark Sasuke]
    steps:
      - name: Mange mon gros fruit ${{matrix.personnes}}
        run: echo "${{matrix.personnes}} mange une ${{matrix.fruits}}, et ${{matrix.personnes}} adore ça ! "